CREATE DATABASE PI_III;

USE PI_III;


CREATE TABLE Cliente(
ID 			INT NOT NULL AUTO_INCREMENT,
Nome 		VARCHAR(255) NOT NULL,
Sobrenome   VARCHAR(255) NOT NULL,
CPF 		VARCHAR (14) UNIQUE NOT NULL,
RG       	VARCHAR (14) UNIQUE NOT NULL,
Complemento	VARCHAR (255),
Cidade 		VARCHAR (30) NOT NULL,
Estado		VARCHAR	(30) NOT NULL,
Endereco	VARCHAR (255) NOT NULL,
CONSTRAINT PK_CLIENTE PRIMARY KEY (ID)
);
CREATE TABLE Usuario(
ID 			INT NOT NULL,
Nome 		VARCHAR(255),
Usuario 	VARCHAR(255) UNIQUE NOT NULL,
Senha		VARCHAR(255) UNIQUE NOT NULL
);

CREATE TABLE Funcionario(
ID 			INT NOT NULL AUTO_INCREMENT,
IdFilial	INT NOT NULL ,
Nome 		VARCHAR(255) NOT NULL,
Sexo 		VARCHAR (9) NOT NULL,
DatNasc 	VARCHAR (10)NOT NULL,
CPF 		VARCHAR (14) UNIQUE NOT NULL,
Cargo		VARCHAR (30) NOT NULL,
Deptmento	VARCHAR (30) NOT NULL,
Celular		VARCHAR	(14) NOT NULL,
Email		VARCHAR (100) NOT NULL,
UserName    VARCHAR (30) NOT NULL,
Senha       VARCHAR (30) NOT NULL,
Ativo		BOOLEAN,
CONSTRAINT PK_FUNCIONARIO PRIMARY KEY (ID)
);

CREATE TABLE Filial(
ID			INT NOT NULL AUTO_INCREMENT,
CNPJ		VARCHAR (20) NOT NULL UNIQUE,
Razao		VARCHAR (100) NOT NULL,
UF			VARCHAR (30) NOT NULL,
Cidade 		VARCHAR (30) NOT NULL,
Resp		VARCHAR (255) NOT NULL,
CONSTRAINT PK_FILIAL PRIMARY KEY (ID)
);

CREATE TABLE Produto(
ID 			INT NOT NULL AUTO_INCREMENT,
NomeProduto	VARCHAR (255) NOT NULL ,
Descricao	VARCHAR (255) NOT NULL,
Preco		VARCHAR (255) NOT NULL,
Categoria	VARCHAR (30) NOT NULL,
Quantidade 	VARCHAR (2) NOT NULL,
CONSTRAINT PK_Produto PRIMARY KEY (ID)
);




